sudo: required
language: node_js
node_js:
  - "node"
before_install:
  - cd Bank/
  - openssl aes-256-cbc -K $encrypted_3f61d339ae2e_key -iv $encrypted_3f61d339ae2e_iv -in config/config.develop.json.enc -out config/config.develop.json -d
  - openssl aes-256-cbc -K $encrypted_6d258aae16e2_key -iv $encrypted_6d258aae16e2_iv -in config/config.production.json.enc -out config/config.production.json -d
  - openssl aes-256-cbc -K $encrypted_6d258aae16e2_key -iv $encrypted_6d258aae16e2_iv -in config/config.test.json.enc -out config/config.test.json -d
  - cd ../

install:
  - cd Bank/
  - npm install phantomjs -g
  - npm install webpack -g
  - npm install
  - webpack
  - cd ../
script:
  - cd Bank/
  - npm test
  - cd ../
before_deploy:
  - NODE_ENV=production make create-dist
deploy:
  on:
    - provider: s3
      branch: master
      condition: NODE_ENV = production
      access_key_id: AKIAI3WDMPRRRPENLPFA
      secret_access_key:
        secure: "TrjRQwUglpk4vViLnyMc1opETzJ9ionkUNaTgbY9LImJyid38T5ov40FlyXKjCT65JKbYiO1L3oVOSeoNd1+1KmlvTU5ctZjn/DlRzn7JwoRbrbXGaOgp9rJykTy1liB/JUeYKv6n5DHbwV8nlsSXnOl5c/nEo2LabN5BiaqzvzatrsQ0RVgvBHr3tcIzBVVo2sHuvukjb2f8RO0X77wnQmQtBIgoIAvVVpjrfdL2yKjfRDCuMzzwgqSjDKgEfhGYKq/DZThI5ISWzyFH1UEPEcoro0EV59ZK3DcL05+BwQv8FCRdhyZO3aSR1/aEIc8SSCAJytiycKBakVlpzhw6syooDDgdPFWp2ZGdpjGOXvVsumkDp28+XlXEECwpWPPCxvTwAK64hi1QRtJnk700bVxUE7iJK7ncQvFGVk6Z7wQQYNGCLIyZEGN0vBLGj7uTj2cafStCecrMstQ8QPOMEbR4teoG5NURbaWo3Q8naIiYlMzJT0UkkjHAWggkK27ThC8S3ZiK2NNb+WEsSiEpTKKDkuemdg2lKwVdAsq8lh4wr28bC1ypkJ1GHpVNzlvrioNoP4NdbNrh+2jZKWUGlGlWNC0ffsLGH9SvOkXFukQN8BaJYqV0TKoT2Yw8yW9BF1sqWuZcfsetAoLU5BEhvy1UzYZkCZ1SBZUKTuYA6Y="
      bucket:
    - provided: codedeploy
      access_key_id: AKIAI3WDMPRRRPENLPFA
      secret_access_key:
        secure: "TrjRQwUglpk4vViLnyMc1opETzJ9ionkUNaTgbY9LImJyid38T5ov40FlyXKjCT65JKbYiO1L3oVOSeoNd1+1KmlvTU5ctZjn/DlRzn7JwoRbrbXGaOgp9rJykTy1liB/JUeYKv6n5DHbwV8nlsSXnOl5c/nEo2LabN5BiaqzvzatrsQ0RVgvBHr3tcIzBVVo2sHuvukjb2f8RO0X77wnQmQtBIgoIAvVVpjrfdL2yKjfRDCuMzzwgqSjDKgEfhGYKq/DZThI5ISWzyFH1UEPEcoro0EV59ZK3DcL05+BwQv8FCRdhyZO3aSR1/aEIc8SSCAJytiycKBakVlpzhw6syooDDgdPFWp2ZGdpjGOXvVsumkDp28+XlXEECwpWPPCxvTwAK64hi1QRtJnk700bVxUE7iJK7ncQvFGVk6Z7wQQYNGCLIyZEGN0vBLGj7uTj2cafStCecrMstQ8QPOMEbR4teoG5NURbaWo3Q8naIiYlMzJT0UkkjHAWggkK27ThC8S3ZiK2NNb+WEsSiEpTKKDkuemdg2lKwVdAsq8lh4wr28bC1ypkJ1GHpVNzlvrioNoP4NdbNrh+2jZKWUGlGlWNC0ffsLGH9SvOkXFukQN8BaJYqV0TKoT2Yw8yW9BF1sqWuZcfsetAoLU5BEhvy1UzYZkCZ1SBZUKTuYA6Y="
      bucket: "eliftechbank"
      key: build/Release/EliftechShop.tar.gz
      application: ElifTechBank
      deployment_group: ElifTech
