sudo: required
language: node_js
node_js:
- node
before_install:
- cd Bank/config/
- openssl aes-256-cbc -K $encrypted_3f61d339ae2e_key -iv $encrypted_3f61d339ae2e_iv -in config.tar.enc -out config.tar -d
- tar -xvf config.tar
- cd ../../
install:
- cd Bank/
- npm install phantomjs -g
- npm install webpack -g
- npm install gulpjs/gulp#4.0 -g
- npm install
- webpack
- cd ../
- cd Shop/
- npm install 
- webpack
- cd ../
- cd Delivery/
- npm install
- gulp build
- cd ../
script:
- cd Bank/
- npm test
- cd ../
- cd Shop/
- npm test
- cd ../
- cd Delivery/
- npm test
- cd ../
before_deploy:
- echo "$TRAVIS_COMMIT" > .commit-hash
- NODE_ENV=production make create-dist
- mv build/Release/EliftechShop.tar build/Release/ET-Shop-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.tar
deploy:
- provider: s3
  access_key_id: AKIAI3WDMPRRRPENLPFA
  secret_access_key: &1
    secure: DjVF4RHs03LWZufKF8ghW8cOA76G3VvjQhxvu2T99JOFla97HD4tF7jEW6BpWNAMtlr5Gj1TBj6xn8+iNJZmBPNhEj48Rpno43s4qFS0dza1xR0SVSvyaisqO20/fds+ujIHtp9VBkZ8WnQoul8hCEc4OXFkf82BhL+mN5Ns/CbMWCtk7h//Eb9RE+wrYU2Uhnw5YsiN0/Cj8xkFzGMQayjyJrEJDhpF0O9nyH9tDvcjHtMDwrJl0cMu5VEf1dEwWro4vbf6GfYGb383sPV1q/kqB3Zb+nyqPmZ6BvEAoekvsAIEhA5TTxfcetBkJWbqEQQnFUIuW7Cr7bW/pukuchKrZ9B2MYr0ihE/Y+rANDAFmo5vbnCUWW7qz5z0ftx6sVfHsLXVlP0qo+JKjbIXdpR1z3XxiMwr8DDCjW8VSlkAK56CTAjeXs3oeCfGwo1HUKD8sfy+JR58s0QExDHlfX3Qhiz6eaFWz/whwvQLbua0dQZA7fPnj96Q7ynpD+Isvj0A4tAL+JwUzjG+KMaUrnl2/RDIctUdvGmjkC8JUW/pLUD1perMGS3DM8a3vHDw9lQBs6xXDMTL3XaSPjhc+Ng8ON4A5HlAszbEkC3F3+yLDOiMwO5VTS0/O4ZYmX3NEojENB0mBDQc1c+xCTLXe3wlG0x3Ios+EG9LCw4vn7s=
  skip_cleanup: true
  local_dir: build/Release
  on: &2
    repo: gameiro9k/ElifTechShop
    branch: master
  bucket: eliftechbank
- provider: codedeploy
  access_key_id: AKIAI3WDMPRRRPENLPFA
  secret_access_key: *1
  region: us-west-2
  bucket: eliftechbank
  key: ET-Shop-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER.tar
  bundle_type: tar
  application: ElifTechBank
  deployment_group: ElifTech
  on: *2
notifications:
  slack: eliftechschool:2vvkGEg06yuxLUfAFXvsLmXz
