version: 0.0
os: linux
files:
  - source: build/Release/Bank
    destination: /home/ubuntu/Bank
hooks:
  BeforeInstall:
    - location: aws/install.sh
  ApplicationStart:
    - location: aws/start.sh
  ApplicationStop:
    - location: aws/stop.sh
