version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: aws/unzip.sh
  ApplicationStart:
    - location: aws/start.sh
  ApplicationStop:
    - location: aws/stop.sh
