    var _ = require('lodash');
    require("./app/app.route.js");
    require("./app/auth/authServices.js");
    require("./app/auth/authControllers.js");
    require("./app/auth/autocompleteDirective.js");
    require("./app/main/mainController.js");
    require("./app/main/mainDirective.js");
    require("./app/main/modalController.js");
    require("./app/main/cabinetController.js");
    require("./app/order/orderService.js");
    require("./app/order/orderController.js");
    require("./app/order/confirmController.js");
    require("./app/catalog/product/productController.js");
    require("./app/catalog/categories/categoryController.js");
    require("./app/catalog/properties/propertyController.js");
    require("./app/catalog/product/productService.js");
    require("./app/catalog/categories/categoryService.js");
    require("./app/catalog/product/productDirective.js");
    require("./app/catalog/product/sortDirective.js");
    require("./app/catalog/categories/categoryDirective.js");
    require("./app/catalog/properties/propertyDirective.js");
    
